version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service-app
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/order_service?createDatabaseIfNotExist=true

#order-service: image: your-order-service-image container_name: order-service environment: SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/yourdatabase SPRING_DATASOURCE_USERNAME: yourusername SPRING_DATASOURCE_PASSWORD: yourpassword depends_on: - mysql ports: - "8080:8080" networks: - my-network networks: my-network: